### ISSUE TITLE
Invalid Player Data when trying to join server

### ISSUE THREAD

**Issue by Spider987** [Ladysnake/Cardinal-Components-API#131]
I'm running a server and recently added this mod alongside Hex casting to the pack we're running. The server starts up fine, but when someone tries to join, it gives an error about invalid player data.

It seems to be Cardinal Components, as it's faling to inatalize.

[13:37:09] [Server thread/FATAL]: [Cardinal Components API] Initialization failed: 
java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/item/ItemComponentInitializer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.getComponentEntrypoints(StaticComponentPluginBase.java:167) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:106) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:308) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at net.minecraft.class_1297.handler$bga000$initDataTracker(class_1297.java:11054) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(class_1429.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_1321.<init>(class_1321.java:31) ~[server-intermediary.jar:?]
	at moriyashiine.bewitchment.common.entity.living.util.BWTameableEntity.<init>(BWTameableEntity.java:31) ~[bewitchment-1.18-23.jar:?]
	at moriyashiine.bewitchment.common.entity.living.SnakeEntity.<init>(SnakeEntity.java:45) ~[bewitchment-1.18-23.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:478) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17846(class_1299.java:487) ~[server-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:580) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299$1.method_31490(class_1299.java:554) ~[server-intermediary.jar:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:553) ~[server-intermediary.jar:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5565.method_31731(class_5565.java:77) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3774(MinecraftServer.java:502) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:333) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:180) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.item.ItemComponentInitializer
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 68 more
[13:37:09] [Server thread/ERROR]: Failed to read chunk [-2, 2]
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/item/ItemComponentInitializer
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3774(MinecraftServer.java:502) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:333) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:180) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/item/ItemComponentInitializer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.getComponentEntrypoints(StaticComponentPluginBase.java:167) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:106) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:308) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at net.minecraft.class_1297.handler$bga000$initDataTracker(class_1297.java:11054) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(class_1429.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_1321.<init>(class_1321.java:31) ~[server-intermediary.jar:?]
	at moriyashiine.bewitchment.common.entity.living.util.BWTameableEntity.<init>(BWTameableEntity.java:31) ~[bewitchment-1.18-23.jar:?]
	at moriyashiine.bewitchment.common.entity.living.SnakeEntity.<init>(SnakeEntity.java:45) ~[bewitchment-1.18-23.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:478) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17846(class_1299.java:487) ~[server-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:580) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299$1.method_31490(class_1299.java:554) ~[server-intermediary.jar:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:553) ~[server-intermediary.jar:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5565.method_31731(class_5565.java:77) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.item.ItemComponentInitializer
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.getComponentEntrypoints(StaticComponentPluginBase.java:167) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:106) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:308) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at net.minecraft.class_1297.handler$bga000$initDataTracker(class_1297.java:11054) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(class_1429.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_1321.<init>(class_1321.java:31) ~[server-intermediary.jar:?]
	at moriyashiine.bewitchment.common.entity.living.util.BWTameableEntity.<init>(BWTameableEntity.java:31) ~[bewitchment-1.18-23.jar:?]
	at moriyashiine.bewitchment.common.entity.living.SnakeEntity.<init>(SnakeEntity.java:45) ~[bewitchment-1.18-23.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:478) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17846(class_1299.java:487) ~[server-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:580) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299$1.method_31490(class_1299.java:554) ~[server-intermediary.jar:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:553) ~[server-intermediary.jar:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5565.method_31731(class_5565.java:77) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 20 more
[13:37:09] [Server thread/INFO]: Time elapsed: 4558 ms
[13:37:09] [Server thread/INFO]: Done (5.707s)! For help, type "help"
[13:37:09] [Server thread/INFO]: Registered thread Server thread
[13:37:09] [Server thread/INFO]: Loaded data from grave data file
[13:37:09] [Server thread/INFO]: Loading Xaero's Minimap - Stage 2/2 (Server)
[13:37:09] [Server thread/INFO]: Loading Xaero's World Map - Stage 2/2 (Server)
[13:39:40] [User Authenticator #1/INFO]: UUID of player MeowcaKitty is 8208a442-2457-44d9-8ef2-d9d8b77fc840
[13:39:40] [Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalStateException: Initialization failed, check the log above for likely causes
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:37) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:308) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-4.1.4-8ccbd4219d1c1f77.jar:?]
	at net.minecraft.class_1297.handler$bga000$initDataTracker(class_1297.java:11054) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.<init>(class_1657.java:200) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.<init>(class_3222.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14613(class_3324.java:454) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$bkb000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:39:40] [Server thread/INFO]: com.mojang.authlib.GameProfile@72c9434d[id=8208a442-2457-44d9-8ef2-d9d8b77fc840,name=MeowcaKitty,properties={textures=[com.mojang.authlib.properties.Property@5ccb52de]},legacy=false] (/73.38.45.210:53444) lost connection: Invalid player data
[13:39:40] [Server thread/WARN]: handleDisconnection() called twice

**Comment by Spider987** [comment]
Fixed by rolling back to a previous version

**Comment by binkybarnes** [comment]
what version
