### ISSUE TITLE
Random error possibly related to mod?

### ISSUE THREAD

**Issue by AchalS-iglu** [Ladysnake/Cardinal-Components-API#132]
Not sure what this has to do with the API but I am getting this error
I get it with or without the API

Thank you!!!

`[17:17:28] [main/INFO]: [STDERR]: java.lang.ClassNotFoundException: dev.onyxstudios.cca.internal.world.ComponentsWorldNetworking::init
[17:17:28] [main/INFO]: [STDERR]:       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.FabricLauncherBase.getClass(FabricLauncherBase.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.md61c996$lambda$create$0$0(class_2477.java:552)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.handler$zbg000$create(class_2477.java:544)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.method_29429(class_2477.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.<clinit>(class_2477.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.read(LanguageReader.java:20)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:49)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:101)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
[17:17:28] [main/INFO]: [STDERR]: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.NetworkingImpl::init
[17:17:28] [main/INFO]: [STDERR]:       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.FabricLauncherBase.getClass(FabricLauncherBase.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.md61c996$lambda$create$0$0(class_2477.java:552)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.handler$zbg000$create(class_2477.java:544)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.method_29429(class_2477.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.<clinit>(class_2477.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.read(LanguageReader.java:20)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:49)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:101)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
[17:17:28] [main/INFO]: [STDERR]: java.lang.ClassNotFoundException: fr.catcore.server.translations.api.ServerTranslations::INSTANCE
[17:17:28] [main/INFO]: [STDERR]:       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.FabricLauncherBase.getClass(FabricLauncherBase.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.md61c996$lambda$create$0$0(class_2477.java:552)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.handler$zbg000$create(class_2477.java:544)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.method_29429(class_2477.java:45)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.<clinit>(class_2477.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.read(LanguageReader.java:20)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:49)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51)
[17:17:28] [main/INFO]: [STDERR]:       at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName0(Native Method)
[17:17:28] [main/INFO]: [STDERR]:       at java.base/java.lang.Class.forName(Class.java:467)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
[17:17:28] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:101)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[17:17:28] [main/INFO]: [STDERR]:       at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)`

Modlist - https://pastebin.com/AgrqPvYV

**Comment by Pyrofab** [comment]
Could I see the whole crash report please ?

**Comment by AchalS-iglu** [comment]
Oh, It's not a crash just an error recieve during server boot everytime. I
will send a whole log when I get home. Thank you!
