### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by URSFR** [Ladysnake/Cardinal-Components-API#147]
I have made a mod pack in which Cardinal Components is included through dependencies of other mods.

We have tested the mod pack of which 2 people had no errors when starting a new world and another 2 people who wanted to start a new world got stuck on the loading screen at 100%. This is the error which repeats itself in the loading screen:

```
[13:54:17] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CcaEntityClientNw.lambda$initClient$2(CcaEntityClientNw.java:50) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.11.jar:?]
```

It is a very strange error because there are people who have errors and others do not. In my case I have no errors.

If necessary I can provide the download link for the mod pack.

**Comment by Pyrofab** [comment]
Hmm... And everyone is using the exact same set of mods ?

**Comment by URSFR** [comment]
yes, everyone uses the same installer which has everyone the same mods

**Comment by Pyrofab** [comment]
Is there some pattern where slower computers get the error, or the reverse ?

**Comment by URSFR** [comment]
nope, who tested it has a gtx1660s and the other rtx2070, both use ssd and both have java 19. I have a gtx1660s, ssd and java 19
