### ISSUE TITLE
Crashes with NBT, no infos about other Mod

### ISSUE THREAD

**Issue by suerion** [Ladysnake/Cardinal-Components-API#150]
Hey, we had updated a few Mods, now it crash with IAE (illegalArgumentExcecption)

Could you please look into the Error-> Thanks 

```[16:45:16] [Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.class_2658.<init>(class_2658.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.toComponentPacket(class_1297.java:8155) ~[server-intermediary.jar:?]
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:196) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:189) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.syncEntityComponents(CardinalComponentsEntity.java:82) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.lambda$init$0(CardinalComponentsEntity.java:57) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
	at net.minecraft.class_3324.handler$bep000$onPlayerLogIn(class_3324.java:2524) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:249) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ehj000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bhd000$modifiedRunLoop(MinecraftServer.java:7885) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Pyrofab** [comment]
Hi, it seems unlikely that CCA itself is the cause of this crash - rather, it seems to me that a mod is trying to synchronize ungodly amounts of data. Do you maybe have Trinkets+Artifacts installed ?

**Comment by suerion** [comment]
Hey, yeah we have also Trinkets and Artifacts installed 

Okey, i thougt so, because Create and CCA causes crashes.

The NBT Error could also be because of the schenatics

**Comment by itsdinkd** [comment]
I am also getting this continously... even with Connectivity installed.

**Comment by suerion** [comment]
Hey, now we got an other error, we don'T have CCA anymore.

```[ServerLoginPacketListenerImpl] Couldn't place player in world
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.<init>(ClientboundCustomPayloadPacket.java:39) ~[?:?]
        at net.minecraft.world.entity.Entity.toComponentPacket(Entity.java:8655) ~[?:?]
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:196) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:189) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
        at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.syncEntityComponents(CardinalComponentsEntity.java:82) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
        at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.lambda$init$0(CardinalComponentsEntity.java:57) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
        at net.minecraft.server.players.PlayerList.handler$bge000$onPlayerLogIn(PlayerList.java:3024) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:249) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:151) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:138) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.redirect$ekp000$handlePlayerJoin(ServerLoginPacketListenerImpl.java:563) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:73) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:248) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:183) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:289) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bii000$modifiedRunLoop(MinecraftServer.java:8385) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:58:29 INFO] [Server thread]: [ServerGamePacketListenerImpl] Schafi1000 lost connection: Invalid player data

**Comment by itsdinkd** [comment]
> Hey, now we got an other error, we don'T have CCA anymore.
> 
> ```
> java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
>         at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.<init>(ClientboundCustomPayloadPacket.java:39) ~[?:?]
>         at net.minecraft.world.entity.Entity.toComponentPacket(Entity.java:8655) ~[?:?]
>         at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:196) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
>         at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:189) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
>         at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.syncEntityComponents(CardinalComponentsEntity.java:82) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
>         at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.lambda$init$0(CardinalComponentsEntity.java:57) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
>         at net.minecraft.server.players.PlayerList.handler$bge000$onPlayerLogIn(PlayerList.java:3024) ~[?:?]
>         at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:249) ~[?:?]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:151) ~[?:?]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:138) ~[?:?]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl.redirect$ekp000$handlePlayerJoin(ServerLoginPacketListenerImpl.java:563) ~[?:?]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:73) ~[?:?]
>         at net.minecraft.network.Connection.tick(Connection.java:248) ~[?:?]
>         at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:183) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:886) ~[server-intermediary.jar:?]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:289) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:819) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$bii000$modifiedRunLoop(MinecraftServer.java:8385) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:257) ~[server-intermediary.jar:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> [17:58:29 INFO] [Server thread]: [ServerGamePacketListenerImpl] Schafi1000 lost connection: Invalid player data
> ```

yes you do. `       at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:196) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]` 


Its most likely another mod has nested it in its jar file as its a dependency

**Comment by UpcraftLP** [comment]
as @Pyrofab mentioned, the root cause does not seem to be CCA, but some other of your mods.

however, you might try using mods like [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric "XL Packets on CurseForge") as a workaround

**Comment by suerion** [comment]
okey, thanks, i will come back again, i will try this mod. Thanks a lot
