### ISSUE TITLE
Issues generating world

### ISSUE THREAD

**Issue by MarcelDev** [Ladysnake/Cardinal-Components-API#166]
While trying to generate a world, i get tons of errors about failing to light chunks

Minecraft version: 1.20.1
Fabric version: 0.15.7
Mod list:

- architectury-9.1.13-fabric
- cc-tweaked-1.20.1-fabric-1.109.6
- duckyperiphs-1.20.1-1.3.1-fabric
- fabric-api-0.92.0+1.20.1
- fabric-language-kotlin-1.10.18+kotlin.1.9.22
- ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
- MTR-fabric-1.20-3.2.2-hotfix-1
- peripheralium-fabric-1.20.1-0.6.15
- Plethora-Fabric-1.9.5
- sc-goodies-1.6.4
- sc-peripherals-1.7.2
- toms_peripherals_fabric-1.20.1-1.2.0
- trinkets-3.7.1
- turtlematic-fabric-1.20.1-1.2.6

Lines of the log relevant to crash:
```
[13:10:32] [Render thread/INFO]: Preparing spawn area: 4%
[13:10:32] [Worker-Main-3/ERROR]: Failed to light chunk [11, -11]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:701) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalStateException: Initialization failed, check the log above for likely causes
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:37) ~[cardinal-components-base-5.2.0-c05853e549fa0aff.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:310) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at net.minecraft.class_1297.handler$zln000$cardinal-components-entity$initDataTracker(class_1297.java:6364) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_1688.<init>(class_1688.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_1688.<init>(class_1688.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_1693.<init>(class_1693.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_1694.<init>(class_1694.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_3353$class_3354.method_14915(class_3353.java:464) ~[client-intermediary.jar:?]
	at net.minecraft.class_3353$class_3354.method_14931(class_3353.java:515) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:320) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:319) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[13:10:32] [Render thread/INFO]: Time elapsed: 71186 ms
[13:10:32] [Server thread/INFO]: Loading custom portal generation
[13:10:32] [Server thread/INFO]: Server started, resetting shared task runner
[13:10:32] [VoiceChatServerThread/INFO]: [voicechat] Voice chat server started at port 61413
[13:10:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/item/ItemComponentInitializer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.7.jar:?]
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.getComponentEntrypoints(StaticComponentPluginBase.java:167) ~[cardinal-components-base-5.2.0-c05853e549fa0aff.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:106) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-5.2.0-c05853e549fa0aff.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:310) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at net.minecraft.class_1297.handler$zln000$cardinal-components-entity$initDataTracker(class_1297.java:6364) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:246) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:133) ~[client-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(class_1429.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_1472.<init>(class_1472.java:112) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:544) ~[client-intermediary.jar:?]
	at net.minecraft.class_1948.method_8661(class_1948.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3754.method_12107(class_3754.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_17033(class_2806.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.item.ItemComponentInitializer
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.7.jar:?]
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.getComponentEntrypoints(StaticComponentPluginBase.java:167) ~[cardinal-components-base-5.2.0-c05853e549fa0aff.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:106) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-5.2.0-c05853e549fa0aff.jar:?]
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:310) ~[?:?]
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55) ~[cardinal-components-entity-5.2.0-2f96e8badc16907b.jar:?]
	at net.minecraft.class_1297.handler$zln000$cardinal-components-entity$initDataTracker(class_1297.java:6364) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:246) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:133) ~[client-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(class_1429.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_1472.<init>(class_1472.java:112) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:544) ~[client-intermediary.jar:?]
	at net.minecraft.class_1948.method_8661(class_1948.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3754.method_12107(class_3754.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_17033(class_2806.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

Crash report: [crash-2024-02-25_13.04.39-server.txt](https://github.com/Ladysnake/Cardinal-Components-API/files/14396485/crash-2024-02-25_13.04.39-server.txt)
Log: [2024-02-25-3.log](https://github.com/Ladysnake/Cardinal-Components-API/files/14396471/2024-02-25-3.log)

**Comment by Pyrofab** [comment]
I believe one of your mods is depending on the item module, but your other mods are only bundling the entity module. Can you try installing the full mod from [modrinth](https://modrinth.com/mod/cardinal-components-api) and see if it happens again ?
