### ISSUE TITLE
crash when trying to enter world

### ISSUE THREAD

**Issue by MasElonn** [Ladysnake/Cardinal-Components-API#167]
when i was about to enter my world and suddenly my minecraft crashed
these are the mods i installed
traveler's backpack and this mod need Cardinal-Components-entity also Cardinal-Components-base

# #--- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-02-28 18:03:26
Description: Starting integrated server

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2204)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277)
	at net.minecraft.class_310.method_29610(class_310.java:2204)
	at net.minecraft.class_7196.method_54611(class_7196.java:368)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_54614(class_7196.java:366)
	at net.minecraft.class_7196.method_54615(class_7196.java:308)
	at net.minecraft.class_7196.method_54618(class_7196.java:242)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:440)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_526.method_19945(class_526.java:53)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 40 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.cardinal_components_entity.json:common.MixinPlayerManager from mod cardinal-components-entity] from phase [DEFAULT] in config [mixins.cardinal_components_entity.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 43 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onPlayerLogIn could not find any targets matching 'Lnet/minecraft/class_3324;method_14570(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;)V' in net.minecraft.class_3324. Using refmap cardinal-components-entity-refmap.json [PREINJECT Applicator Phase -> mixins.cardinal_components_entity.json:common.MixinPlayerManager from mod cardinal-components-entity -> Prepare Injections ->  -> handler$zdc000$cardinal-components-entity$onPlayerLogIn(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2204)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277)
	at net.minecraft.class_310.method_29610(class_310.java:2204)
	at net.minecraft.class_7196.method_54611(class_7196.java:368)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_54614(class_7196.java:366)
	at net.minecraft.class_7196.method_54615(class_7196.java:308)
	at net.minecraft.class_7196.method_54618(class_7196.java:242)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:440)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_526.method_19945(class_526.java:53)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
Mixins in Stacktrace:
	net.minecraft.class_310:
		xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.fabric.mixins.json)
		com.illusivesoulworks.spectrelib.mixin.SpectreLibMixinMinecraft (spectrelib.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (languagereload.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReload (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dynamic_fps.impl.mixin.MinecraftMixin (dynamic_fps.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (modernfix-common.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (mixins/fabric/nochatreports-fabric.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (zoomify.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (modernfix-common.mixins.json)
		dev.isxander.controlify.mixins.feature.screenop.MinecraftMixin (controlify.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (fastquit.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (immediatelyfast-common.mixins.json)
		com.github.dimadencep.mods.rrls.fabric.mixins.MinecraftClientMixin (rrls.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (fastquit.mixins.json)
		dev.isxander.controlify.mixins.feature.rumble.MinecraftMixin (controlify.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (mixins/common/nochatreports.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (languagereload.mixins.json)
		xaero.common.mixin.MixinMinecraftClient (xaerominimap.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		ca.fxco.moreculling.mixin.blockstates.MinecraftClient_loadBlocksMixin (moreculling.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (optigui.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.blast_search_trees.MinecraftMixin (modernfix-common.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		ca.fxco.moreculling.mixin.MinecraftClient_managersMixin (moreculling.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		mezz.jei.fabric.mixin.MinecraftMixin (jei.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		dev.isxander.controlify.mixins.feature.input.MinecraftMixin (controlify.mixins.json)
		dev.isxander.controlify.mixins.core.MinecraftMixin (controlify.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		org.embeddedt.modernfix.fabric.mixin.core.MCMixin_Fabric (modernfix-fabric.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		dev.isxander.controlify.mixins.feature.virtualmouse.MinecraftMixin (controlify.mixins.json)
		com.github.dimadencep.mods.rrls.mixins.MinecraftClientMixin (rrls-common.mixins.json)
		glitchcore.mixin.client.MixinMinecraft (glitchcore.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
		de.dafuqs.paginatedadvancements.mixin.MinecraftClientMixin (paginatedadvancements.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (modernfix-common.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (mixins.fabrishot.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_leaks.MinecraftMixin (modernfix-common.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.feature.measure_time.MinecraftMixin_Fabric (modernfix-fabric.mixins.json)
	net.minecraft.server.MinecraftServer:
		net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.MinecraftServerMixin (modernfix-fabric.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.MinecraftServerMixin (fabric-registry-sync-v0.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftServerMixin (balm.fabric.mixins.json)
		net.fabricmc.fabric.mixin.biome.modification.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.ClientMinecraftServerMixin (modernfix-fabric.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftServerAccessor (fastquit.mixins.json)
		terrablender.mixin.MixinMinecraftServer (terrablender_fabric.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftServerMixin (modernfix-common.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftServerMixin (fastquit.mixins.json)
		xaero.map.mixin.MixinMinecraftServer (xaeroworldmap.mixins.json)
		xaero.common.mixin.MixinMinecraftServer (xaerominimap.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (fabric-message-api-v1.mixins.json)
	net.minecraft.class_7196:
		com.kingcontaria.fastquit.mixin.IntegratedServerLoaderMixin (fastquit.mixins.json)
		terrablender.mixin.MixinWorldOpenFlows (terrablender.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.WorldOpenFlowsMixin (modernfix-common.mixins.json)
	net.minecraft.class_1255:
		dynamic_fps.impl.mixin.bugfix.BlockableEventLoopMixin (dynamic_fps.mixins.json)
	net.minecraft.class_528$class_4272:
		dev.isxander.controlify.mixins.feature.screenop.vanilla.WorldSelectionListEntryMixin (controlify.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_screen_skipped.WorldSelectionListMixin (modernfix-common.mixins.json)
		com.kingcontaria.fastquit.mixin.WorldListWidgetWorldEntryMixin (fastquit.mixins.json)
	net.minecraft.class_526:
		dev.isxander.controlify.mixins.feature.screenop.vanilla.SelectWorldScreenAccessor (controlify.mixins.json)
		dev.isxander.controlify.mixins.feature.screenop.vanilla.SelectWorldScreenMixin (controlify.mixins.json)
	net.minecraft.class_4264:
		dev.isxander.controlify.mixins.feature.screenop.vanilla.AbstractButtonMixin (controlify.mixins.json)
		dev.isxander.controlify.mixins.feature.guide.screen.AbstractButtonMixin (controlify.mixins.json)
	net.minecraft.class_339:
		dev.isxander.controlify.mixins.feature.guide.screen.AbstractWidgetMixin (controlify.mixins.json)
	net.minecraft.class_4069:
		dev.isxander.controlify.mixins.feature.screenop.ContainerEventHandlerMixin (controlify.mixins.json)
		dev.isxander.yacl3.fabric.mixin.ContainerEventHandlerMixin (yacl-fabric.mixins.json)
	net.minecraft.class_312:
		net.blay09.mods.balm.mixin.MouseHandlerAccessor (balm.fabric.mixins.json)
		com.github.dimadencep.mods.rrls.mixins.compat.SplashUseFix (rrls-common.mixins.json)
		net.blay09.mods.balm.mixin.MouseHandlerMixin (balm.fabric.mixins.json)
		dev.isxander.controlify.mixins.core.MouseHandlerMixin (controlify.mixins.json)
		dev.isxander.controlify.mixins.feature.virtualmouse.MouseHandlerAccessor (controlify.mixins.json)
		dev.isxander.zoomify.mixins.zoom.MouseMixin (zoomify.mixins.json)
		dev.isxander.controlify.mixins.feature.virtualmouse.MouseHandlerMixin (controlify.mixins.json)
		com.tiviacz.travelersbackpack.mixin.MouseMixin (travelersbackpack.mixins.json)
		net.fabricmc.fabric.mixin.screen.MouseMixin (fabric-screen-api-v1.mixins.json)
	net.minecraft.class_437:
		net.fabricmc.fabric.mixin.screen.ScreenAccessor (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.screen.ScreenMixin (fabric-screen-api-v1.mixins.json)
		dev.isxander.controlify.mixins.feature.screenop.ScreenAccessor (controlify.mixins.json)
		dev.isxander.controlify.mixins.feature.screenop.ScreenMixin (controlify.mixins.json)
		dynamic_fps.impl.mixin.ScreenMixin (dynamic_fps.mixins.json)
		net.blay09.mods.balm.mixin.ScreenAccessor (balm.fabric.mixins.json)
		mezz.jei.fabric.mixin.ScreenMixin (jei.mixins.json)
		dev.isxander.controlify.mixins.feature.virtualmouse.snapping.ScreenMixin (controlify.mixins.json)

**Comment by Pyrofab** [comment]
Hello, I will need a bit more information here. Like what version of Cardinal Components API did you install, which Minecraft version is this, and does it happen with *only* traveler's backpack and CCA installed ?

**Comment by MasElonn** [comment]
the version is 5.4.0 minecraft 1.20.4 fabric

**Comment by luceos** [comment]
Same with minecraft 1.20.2, cardinal api 5.3.0 and fabric 0.15.11, also for travelers backpack (9.2.4)
