### ISSUE TITLE
[Question/Crash] ComponentKey Class not found

### ISSUE THREAD

**Issue by yuesha-yc** [Ladysnake/Cardinal-Components-API#67]
Hi, I just ran my mod normally today and get this error. The mod runs smoothly last time I built it. 

I run with 2.7.9 CCA. I refreshed dependencies. 

```
[21:51:32] [main/WARN] (mixin) Error loading class: dev/onyxstudios/cca/api/v3/component/ComponentKey (java.lang.ClassNotFoundException: dev/onyxstudios/cca/api/v3/component/ComponentKey)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
        ... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.minecraft.client.main.Main.main(Main.java:118)
        ... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for elt.mixins.json:MixinPlayerEntity during activity: [Transform -> Method update(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> dev/onyxstudios/cca/api/v3/component/ComponentKey::get(Ljava/lang/Object;)Lnerdhub/cardinal/components/api/component/Component;]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 15 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.component.ComponentKey
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:720)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.component.ComponentKey
        ... 25 more

FAILURE: Build failed with an exception.
```
Codebase is here:
https://github.com/MoegTech/EnergyLevelTransition/tree/dev/yuesha

**Comment by Pyrofab** [comment]
Hmm, this may be due to the fact you included the big jar. Have you tried including individual modules instead ?

**Comment by yuesha-yc** [comment]
I still get the same result. I switched to depending on only the base module and entity module (which I used).

**Comment by MagicQuartz** [comment]
I'm getting the exact same error.
