### ISSUE TITLE
Cardinal components contain invalid entries?

### ISSUE THREAD

**Issue by Cloud567818** [Ladysnake/Cardinal-Components-API#81]
Not sure why its doing this tbh, and I don't see any other issue saying anything about it

[01:00:17] [main/INFO]: Loading for game Minecraft 1.16.5
[01:00:18] [ForkJoinPool-1-worker-9/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[01:00:18] [ForkJoinPool-1-worker-8/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[01:00:18] [main/INFO]: [FabricLoader] Loading 109 mods: fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.10.184, materialisation@3.0.3, trinkets@2.6.7, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, crowdin-translate@1.2, fabric-dimensions-v1@2.0.6+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, jumploader@2.1.3, cardinal-components-level@2.7.13, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, armsoffire@1.0.5, cardinal-components-scoreboard@2.7.13, fabric@0.32.0+1.16, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, tk_valoeghese_zoesteriaconfig@1.3.2, repurposed_structures@1.16.5-1.9.0, customportalapi@0.0.1-beta20-1.16, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, extraorigins@1.16.5-10, roughlyenoughitems-runtime@5.10.184, angerable-patch@1.1.0-1.16.4, cloth-client-events-v0@1.5.47, voyager@1.0.0, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, oro_config@1.2.0, mostructures@1.1.0+mc.1.16.5, fabric-language-kotlin@1.5.0+kotlin.1.4.31, origins@0.6.2, fabric-key-binding-api-v1@1.0.4+9354966b7d, cloth-config2@4.11.14, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, org_jetbrains_kotlin_kotlin-reflect@1.4.31, cardinal-components-entity@2.7.13, assetvalidator@1.0.2, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, cardinal-components-base@2.7.13, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, the_aether@1.16.5-1.0.1, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, geckolib3@3.0.23, fabric-renderer-api-v1@0.4.1+ca58154a7d, cardinal-components-block@2.7.13, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, pehkui@1.9.0+21w10a, waystones@1.1.1.1, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, cpm@0.0.9b, fabric-textures-v0@1.0.6+ca58154a7d, cardinal-components-item@2.7.13, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.0.1, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, cardinal-components-chunk@2.7.13, fabric-renderer-registries-v1@2.2.1+ca58154a7d, cardinal-components-util@2.7.13, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, chiseldecor@1.1.3, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, roughlyenoughitems-default-plugin@5.10.184, minecraft@1.16.5, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.1.0+f9b3753b7d, cloth-basic-math@0.5.1, cotton-resources@1.7.1, invtrashslot@1.0.2, fabric-screen-api-v1@1.0.0+c045166c7d, origins-classes@1.1.1, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-item-api-v1@1.2.1+ca58154a7d, roughlyenoughitems@5.10.184, libgui@3.2.2+1.16.3, cardinal-components@2.7.13, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, seedy-behavior@1.0.1, polymorph@0.0.10-1.16.5, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, cardinal-components-world@2.7.13, fabric-biome-api-v1@3.1.1+ca58154a7d, advanced_runtime_resource_pack@0.3.7, appleskin@1.0.11, byg@1.1.7, voxelmap@1.10.15, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, whiplash@1.0.0
[01:00:18] [main/WARN]: Mod `waystones` (1.1.1.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[01:00:18] [main/WARN]: Mod `cpm` (0.0.9b) does not respect SemVer - comparison support is limited.
[01:00:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/cloud/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[01:00:18] [main/WARN]: Error loading class: net/minecraft/class_5617$class_5618 (java.lang.ClassNotFoundException: net/minecraft/class_5617$class_5618)
[01:00:19] [main/INFO]: I used the json to destroy the json
[01:00:21] [main/FATAL]: Mixin apply failed cotton-resources.common.json:MixinVanillaOregen -> net.minecraft.class_3864: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on mixinDefaultOres could not find any targets matching 'Lnet/minecraft/class_3864;method_17006(Lnet/minecraft/class_1959;)V' in net.minecraft.class_3864. Using refmap cotton-resources+unspecified-refmap.json [PREINJECT Applicator Phase -> cotton-resources.common.json:MixinVanillaOregen -> Prepare Injections ->  -> handler$zio000$mixinDefaultOres(Lnet/minecraft/class_1959;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on mixinDefaultOres could not find any targets matching 'Lnet/minecraft/class_3864;method_17006(Lnet/minecraft/class_1959;)V' in net.minecraft.class_3864. Using refmap cotton-resources+unspecified-refmap.json [PREINJECT Applicator Phase -> cotton-resources.common.json:MixinVanillaOregen -> Prepare Injections ->  -> handler$zio000$mixinDefaultOres(Lnet/minecraft/class_1959;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_5478.method_30706(class_5478.java:730) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_5504.<clinit>(class_5504.java:17) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30567(class_5458.java:52) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$210/199041063.get(Unknown Source) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$212/732688777.accept(Unknown Source) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]

**Comment by UpcraftLP** [comment]
This issue only occurs when mods ship very old versions of Cardinal Components, and has been fixed since October 2020.

We cannot do anything about the log spam on our side, you'd have to find the responsible mods and ask them to update their version of Cardinal Components API.
